### PR TITLE
feat: facial recognition

### PR DESCRIPTION
**Pull request by martabal**
Face recognition implementation.

### CODE REVIEW

**Comment by hydazz** [comment]
@martabal why is gunicorn not used anymore?

**Comment by martabal** [comment]
> @martabal why is gunicorn not used anymore?

They moved from Flask to FastAPI

**Comment by martabal** [comment]
I added a symbolic link between /config/faces and /cache so users don't have to add modify their setup. This is not ideal and should be temporary

**Comment by martabal** [comment]
> I added a symbolic link between `/config/faces` and `/cache` so users don't have to modify their volumes. This is not ideal and should be temporary (ideally the folder containing the faces should be set with environment variables).

Fixed, using now env `MACHINE_LEARNING_CACHE_FOLDER`. Immich devs are fast ahah

**Comment by martabal** [comment]
@hydazz What do you thing about using `/home` for cache ?

**Comment by martabal** [comment]
To be merged when fr is released (probably `v1.55`)

**Pull request merged**
