### PR TITLE
fix: use different processes for microservices and api (main)

### LINKED ISSUE #374: ERROR: EADDRINUSE: address already in use :::8080 following v1.106.x updates
Since the latest series of updates, I've had the following errors when running Immich via CA Docker on Unraid.

- Unraid running v6.12.10
- Immich installation has been running successfully for more than a year
- Separate Postgres and REDIS Docker containers
- All three containers running as hosts to give separate IP addresses outside of a DHCP pool (no conflicts)

> Error: listen EADDRINUSE: address already in use :::8080
>     at Server.setupListenHandle [as _listen2] (node:net:1898:16)
>     at listenInCluster (node:net:1946:12)
>     at Server.listen (node:net:2044:7)
>     at ExpressAdapter.listen (/app/immich/server/node_modules/@nestjs/platform-express/adapters/express-adapter.js:95:32)
>     at /app/immich/server/node_modules/@nestjs/core/nest-application.js:180:30
>     at new Promise (<anonymous>)
>     at NestApplication.listen (/app/immich/server/node_modules/@nestjs/core/nest-application.js:170:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async bootstrap (/app/immich/server/dist/workers/api.js:53:20) {
>   code: 'EADDRINUSE',
>   errno: -98,
>   syscall: 'listen',
>   address: '::',
>   port: 8080
> }
> node:internal/process/promises:289
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> Error: listen EADDRINUSE: address already in use :::8080
>     at Server.setupListenHandle [as _listen2] (node:net:1898:16)
>     at listenInCluster (node:net:1946:12)
>     at Server.listen (node:net:2044:7)
>     at ExpressAdapter.listen (/app/immich/server/node_modules/@nestjs/platform-express/adapters/express-adapter.js:95:32)
>     at /app/immich/server/node_modules/@nestjs/core/nest-application.js:180:30
>     at new Promise (<anonymous>)
>     at NestApplication.listen (/app/immich/server/node_modules/@nestjs/core/nest-application.js:170:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async bootstrap (/app/immich/server/dist/workers/api.js:53:20) {
>   code: 'EADDRINUSE',
>   errno: -98,
>   syscall: 'listen',
>   address: '::',
>   port: 8080
> }
> 
> Node.js v20.14.0
> api worker exited with code 1

It seems to be connected to the microservices change, but I am unable to find a fix.

Have tried a number of things, including:

- Waiting for further updates (twice now without a fix)
- Removing variables and using new environment variables specified in Immich main branch "Breaking Changes" note.
- Cycling through alternative ports and port combinations to ensure no other conflict exists - each time the port number at the end of the above "already in use" address changes to show the updated "IMMICH_PORT" or "MACHINE_LEARNING_PORT" when only one was used.
- Attempted to offload Machine Learning to an external machine
- Removing entire container (and user template) and beginning again

One curious note is that no matter the port specified (with Immich confirmed as accessible via), the port mapping in Unraid's Docker dashboard always shows 8080.

Screenshot 2024-06-17 at 23 20 25

At some point it appears to have been working as I have new thumbnails for ~30 images added after the error began, but nothing new is being generated. Have left it to run overnight at times with nothing but the same error message appearing in the logs the next morning.

Is this likely to be a limitation of the Community Applications plugin? If so, is there a guide on moving from that to a Docker Stack?

### PR DESCRIPTION
**Pull request by martabal**
trying to fix #374

### CODE REVIEW

**Comment by hydazz** [comment]
ready to merge @martabal ?

**Comment by martabal** [comment]
> ready to merge @martabal ?

Yep.

You can merge all my PRs, I'll open new PRs for cuda, noml and openvino this evening to add this change.

**Comment by hydazz** [comment]
> > ready to merge @martabal ?
> 
> Yep.
> 
> You can merge all my PRs, I'll open new PRs for cuda, noml and openvino this evening to add this change.

Ill sync this change to the other repos 🙂

**Comment by martabal** [comment]
> Ill sync this change to the other repos 🙂

Nice! Thank you

**Pull request merged**
