### PR TITLE
feat: skip chown at startup

### PR DESCRIPTION
**Pull request by rexzhang**
#112

### CODE REVIEW

**Comment by martabal** [comment]
I think you over-complexified this feature, why do you want to skip chown for all folders ? I thought it was only for `/photos` ?

**Comment by hydazz** [comment]
@martabal we could probably just replace `chown` with `lsiown`, `lsiown` redirects to `chown`, but it exits 0, so the container will continue to startup if it cant chown these folders

**Comment by martabal** [comment]
> @martabal we could probably just replace `chown` with `lsiown`, `lsiown` redirects to `chown`, but it exits 0, so the container will continue to startup if it cant chown these folders

for `/photos` or for all `chown` commands ?

**Comment by martabal** [comment]
I opened a PR which simplifies a lot this one #125

**Comment by hydazz** [comment]
```
chown -R abc:abc \
    /photos \
    /run/immich \
    /app/typesense

**Comment by martabal** [comment]
> thats it, all we need

@hydazz Fixed in my PRs

**Comment by rexzhang** [comment]
> I think you over-complexified this feature, why do you want to skip chown for all folders ? I thought it was only for `/photos` ?

too many file need to check, so too slow

**Comment by hydazz** [comment]
> > I think you over-complexified this feature, why do you want to skip chown for all folders ? I thought it was only for `/photos` ?
> 
> too many file need to check, so too slow

that is why we exclude the directories that dont need chowning, and would take a while to chown

```
    find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +
    find /config -path "cuda-venv" -prune -o -exec chown abc:abc {} +
```

that script, as is completes within a second from our testing

**Comment by rexzhang** [comment]
> > > I think you over-complexified this feature, why do you want to skip chown for all folders ? I thought it was only for `/photos` ?
> > 
> > 
> > too many file need to check, so too slow
> 
> that is why we exclude the directories that dont need chowning, and would take a while to chown
> 
> ```
>     find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +
>     find /config -path "cuda-venv" -prune -o -exec chown abc:abc {} +
> ```
> 
> that script, as is completes within a second from our testing

I don't know why, it's very slow(3mins) at my system(truenas scale/N5105/ssd).

**Comment by hydazz** [comment]
> > > > I think you over-complexified this feature, why do you want to skip chown for all folders ? I thought it was only for `/photos` ?
> 
> > > 
> 
> > > 
> 
> > > too many file need to check, so too slow
> 
> > 
> 
> > that is why we exclude the directories that dont need chowning, and would take a while to chown
> 
> > 
> 
> > ```
> 
> >     find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +
> 
> >     find /config -path "cuda-venv" -prune -o -exec chown abc:abc {} +
> 
> > ```
> 
> > 
> 
> > that script, as is completes within a second from our testing
> 
> 
> 
> I don't know why, it's very slow(3mins) at my system(truenas scale/N5105/ssd).

Can you set `S6_VERBOSITY=2` and find out which script is actually holding back boot, it’ll say which script is currently being executed in the logs. You can also add `set -xe` at the top of the script in question to see which command is taking its time (or just run the command manually)

**Comment by rexzhang** [comment]
here `s6-rc: info: service init-config-immich: starting`

and this command
`118 ?        D      0:00 chown abc:abc /app/immich /app/immich/machine-learning /app/immich/machine-learning/app /app/immich/machine-learning/app/main.py /app/immich/machine-learning/app/schemas.py /app/immich/machine-learning/app/models /app/immich/machine-learning/app/models/facial_recognition.py /app/immich/machine-learning/app/models/cache.py /app/immich/machine-learning/app/models/clip.py /app/immich/machine-learning/app/models/__init__.py /app/immich/machine-learning/app/models/base.py /app/immich/machine-learning/app/models/image_classification.py /app/immich/machine-learning/app/test_main.py /app/immic
`

**Comment by hydazz** [comment]
@rexzhang 

run `apt update && apt install -y time`, then

```
root@d9860f2e066e:/# time find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +

real    0m0.008s
user    0m0.000s
sys     0m0.007s
```

I dont see how it could ever go over a minute, based that it takes 0.007s for me

**Comment by hydazz** [comment]
are we happy with https://github.com/imagegenius/docker-immich/pull/125 as a solution to this?

**Comment by rexzhang** [comment]
> are we happy with #125 as a solution to this?

Yes! Through the test. "lsiown" is a better solution.

**Pull request closed without merging**
