### PR TITLE
fix: move from flask to fastapi

### PR DESCRIPTION
**Pull request by martabal**
Hotfix for [v1.55](https://github.com/immich-app/immich/releases/tag/v1.55.0)

### CODE REVIEW

**Comment by martabal** [comment]
@hydazz Is CI broken ? He doesn't use my commit

**Comment by martabal** [comment]
@hydazz Is CI broken ? It doesn't use my commit

**Comment by hydazz** [comment]
> @hydazz Is CI broken ? It doesn't use my commit

looks like its working, you have not updated the arm dockerfile...

**Comment by martabal** [comment]
My bad I completely forgot it 😅

**Comment by martabal** [comment]
CI is never wrong ahah

**Pull request merged**
