### PR TITLE
fix: support raw images

### PR DESCRIPTION
**Pull request by martabal**
fix for #109 #107.

### CODE REVIEW

**Comment by martabal** [comment]
Immich goal when stable is reached is to have all its dependencies up-to-date. One of them is sharp and requires latest libvips version. The libvips package version for ubuntu is always months or years behind the latest version, I think it makes sense we still build libvips from source even after the imagemagick issue is fixed upstream.

As of today (Jun 26 2023), Immich uses sharp version v0.31.3, but latest sharp version (v0.32) requires libvips v8.14.2 and the latest version available for ubuntu is v8.14.1

**Comment by hydazz** [comment]
why not just grab the latest version from `https://archive.ubuntu.com/ubuntu/pool/universe/v/vips/libvips42_8.14.2-1_amd64.deb`?

**Comment by martabal** [comment]
Can you automatically grab the latest version ? I didn't know you could dot it, and it would be much better :)

**Comment by hydazz** [comment]
we can either grab the latest from that ubuntu repo or create something similar to the aports repo for dpkg packages, either way the dockerfile here is getting a bit crowded for a niche feature

**Comment by martabal** [comment]
I just tested it, and it does not seems to work, still get the error : 
```bash
immich      | [Nest] 772  - 06/26/2023, 11:05:19 PM   ERROR [JobService] Unable to run job handler: Error: Input file contains unsupported image format
immich      | [Nest] 772  - 06/26/2023, 11:05:19 PM   ERROR [JobService] Error: Input file contains unsupported image format
```

**Comment by martabal** [comment]
> for a niche feature

In my opinion, raw support is not merely a niche feature; it's actually quite significant. I'm genuinely curious about how much this is a crucial feature among users.

**Comment by hydazz** [comment]
do all these dev packages need to be kept
```
...
    libcfitsio-dev \
    libexif-dev \
    libexpat1-dev \
    libfftw3-dev \
    libgirepository1.0-dev \
    libglib2.0-dev \
    libgsf-1-dev \
    libheif-dev \
    libimagequant-dev \
    libjpeg-dev \
    libjpeg-turbo8-dev \
    libjxl-dev \
    libmatio-dev \
    libopenexr-dev \
    libopenjp2-7-dev \
    libopenslide-dev \
    liborc-dev \
    libpango1.0-dev \
    libpng-dev \
    libpoppler-glib-dev \
...
```

**Comment by martabal** [comment]
Those are the same that get installed when libvips-dev is installed, I think we can get rid of some of them, the only effect is when building libvips, it won't enable some functionalities

**Comment by hydazz** [comment]
@martabal we'll merge this one, but as soon as its fixed upstream we need to clean up the dockerfile again, or create our own dpkg/deb that works

**Comment by martabal** [comment]
> @martabal we'll merge this one, but as soon as its fixed upstream we need to clean up the dockerfile again, or create our own dpkg/deb that works

Absolutely, this is just a temporary fix

**Pull request merged**
