### PR TITLE
chore: update heif package (noml)

### PR DESCRIPTION
**Pull request by martabal**
https://github.com/immich-app/immich/pull/2430 has been merged and will be released for v1.56.1 / 1.57

### CODE REVIEW

**Comment by martabal** [comment]
@hydazz can be merged

**Comment by hydazz** [comment]
@martabal why did ci try find `JWT_SECRET`?
https://ci-tests.imagegenius.io/immich/noml-v1.56.0-pkg-54abd8b2-pr-78/amd64-noml-v1.56.0-pkg-54abd8b2-pr-78.log.html

**Comment by martabal** [comment]
`JWT_SECRET` has been completly removed 🤔.

**Comment by hydazz** [comment]
@martabal the variable check script does not have JWT_SECRET defined so CI should not have said that

**Pull request merged**
