### PR TITLE
feat: remove unused `JWT_SECRET` (noml)

### PR DESCRIPTION
**Pull request by martabal**
Same as #72 .

### CODE REVIEW

**Comment by hydazz** [comment]
@martabal 🤔

**Comment by martabal** [comment]
@hydazz My bad, when I opened the PR I forgot to change the base branch, and just closed the PR. After the PR opened, can we edit the branch ?

**Comment by hydazz** [comment]
> @hydazz My bad, when I opened the PR I forgot to change the base branch, and just closed the PR. After the PR opened, can we edit the branch ?

Haha wdym edit the branch, you opened another pr for this?

**Comment by martabal** [comment]
I wanted to merge my branch martabal:feat/rm-jwt-noml to imagenius:noml, but forgot to change the destination branch. So I closed this one and opened #74. Can I modify the destination branch from `imagegenius:main` to `imagegenius:noml` after PR has been opened ?

**Pull request closed without merging**
