### PR TITLE
feat!: use depedencies in base image repo

### PR DESCRIPTION
**Pull request by martabal**
Immich will use a base image and all the build scripts will be in [this repo](https://github.com/immich-app/base-images). 

Related PR : https://github.com/immich-app/immich/pull/4456

### CODE REVIEW

**Comment by hydazz** [comment]
@martabal perhaps we create a baseimage for immich as well?

**Comment by martabal** [comment]
> @martabal perhaps we create a baseimage for immich as well?

It would be great !

**Comment by hydazz** [comment]
use https://github.com/imagegenius/docker-immich/pull/206 instead of this?

**Comment by martabal** [comment]
Yep

**Pull request closed without merging**
