### PR TITLE
chore!: remove typesense (main)

### PR DESCRIPTION
**Pull request by martabal**
This PR adds multiple improvements / fixes : 

- [Immich v1.91 won't use typesense anymore](https://github.com/immich-app/immich/releases/tag/v1.90.0)
- Fix the sharp install for v1.91 https://github.com/immich-app/immich/pull/5509/files
- Extract metadata from jxl images #217

To be merged when v1.91 is released

### CODE REVIEW

**Comment by traktuner** [comment]
Maybe the readme can also be adapted in this PR to reflect the necessary breaking changes (which this time also concerns the AIO users)
For instance:

here to mention pgvector.rs:
https://github.com/imagegenius/docker-immich/blob/9e1ef0728fcfb42c755abfdec823bb48c32e66cf/README.md?plain=1#L41

update the docker-compose and docker guide:
https://github.com/imagegenius/docker-immich/blob/9e1ef0728fcfb42c755abfdec823bb48c32e66cf/README.md?plain=1#L105
https://github.com/imagegenius/docker-immich/blob/9e1ef0728fcfb42c755abfdec823bb48c32e66cf/README.md?plain=1#L162

**Comment by martabal** [comment]
> Maybe the readme can also be adapted in this PR to reflect the necessary breaking changes (which this time also concerns the AIO users) For instance:
> 
> here to mention pgvector.rs:
> 
> https://github.com/imagegenius/docker-immich/blob/9e1ef0728fcfb42c755abfdec823bb48c32e66cf/README.md?plain=1#L41
> 
> update the docker-compose and docker guide:
> 
> https://github.com/imagegenius/docker-immich/blob/9e1ef0728fcfb42c755abfdec823bb48c32e66cf/README.md?plain=1#L105
> 
> https://github.com/imagegenius/docker-immich/blob/9e1ef0728fcfb42c755abfdec823bb48c32e66cf/README.md?plain=1#L162

Thanks, I was convinced I had done it

**Comment by martabal** [comment]
> I just want to add that, it seems that v1.91 will also change to use a postgres database with vector extension (`tensorchord/pgvecto-rs`). The migration seems trivial but might involve intervention.
> 
> I'm using the `alpine` variant, so I assume using plain postgres database should continue to work, but need to double check that after v1.91 is finally released.

I just tried it, and no, you'll need to use the custom postgres database

**Comment by hydazz** [comment]
outstanding success

**Pull request merged**
