### PR TITLE
feat: add missing driver for hardware acceleration (main)

### PR DESCRIPTION
**Pull request by martabal**
Hardware acceleration is coming in a future release and it needs the non-free intel driver to work.
You can test it this new feature by pulling `docker.io/martabal/immich-dev:with-intel-driver` and `docker.io/martabal/immich-dev:without-intel-driver`.

### CODE REVIEW

**Review by hydazz — APPROVED** [review]

**Comment by martabal** [comment]
Seems it needs `mesa-va-drivers` too

**Comment by martabal** [comment]
@hydazz Can be merged. Will noml support transcoding hardware acceleration  ?

**Comment by hydazz** [comment]
> @hydazz Can be merged. Will noml support transcoding hardware acceleration  ? 

No, torch/tensor is not compiled tor musl, and the models are also not compiled for musl

**Comment by martabal** [comment]
> > @hydazz Can be merged. Will noml support transcoding hardware acceleration  ?
> 
> No, torch/tensor is not compiled tor musl, and the models are also not compiled for musl

Ah :/. Should we move from alpine to ubuntu then ?

**Comment by hydazz** [comment]
> > > @hydazz Can be merged. Will noml support transcoding hardware acceleration  ?
> 
> > 
> 
> > No, torch/tensor is not compiled tor musl, and the models are also not compiled for musl
> 
> 
> 
> Ah :/ Should we move from alpine to ubuntu then ?

Missed that you said transcoding thought you mean machine learning 🫣

Not sure if hardware acceleration is supported, ffmpeg might work

**Comment by hydazz** [comment]
@martabal ready to merge?

**Comment by martabal** [comment]
Yep !

**Pull request merged**
