### PR TITLE
feat: ability to disable machine-learning

### PR DESCRIPTION
**Pull request by martabal**
Disable machine-learning process with the `DISABLE_MACHINE_LEARNING` environment variable.

### CODE REVIEW

**Comment by martabal** [comment]
Revert to have the new feature in a new PR

**Comment by hydazz** [comment]
@martabal, i think that setting the service to a `oneshot` so its only ran once, then it can be easily exited with an `exit 0` seems to be the best approach. Thoughts?

**Comment by martabal** [comment]
Much better !

**Comment by martabal** [comment]
@hydazz wait, I just realized, if the machine-learning is enabled and it stops because of an error, will it restart ?

**Comment by hydazz** [comment]
> @hydazz wait, I just realized, if the machine-learning is enabled and it stops because of an error, will it restart ?

Do you think that we still need this? The noml branch is probably better for people who don't have avx or just don't want to run object detection

**Comment by martabal** [comment]
Yep you're right. Closing this PR and opening a new one to fully disable the machine-learning.

**Pull request closed without merging**
