### PR TITLE
feat: support openvino

### PR DESCRIPTION
**Pull request by martabal**
support openvino natively

### CODE REVIEW

**Comment by hydazz** [comment]
sorry, forgot to disable arm!
that needed to be done in the main branch of the pr https://github.com/imagegenius/docker-immich/commit/a4d570187f1ef419ed56017f9bd76c5dbad3910f

**Comment by martabal** [comment]
Ahah no worries, I didn't understand why CI was failing. Thanks!

**Comment by hydazz** [comment]
@martabal finally ready haha?

**Comment by martabal** [comment]
> @martabal finally ready haha?

Yes! 

FYI, the onnxruntime-openvino dependency is broken for some GPUs (at least mine, see https://github.com/immich-app/immich/issues/8226). This should be fixed with the next update. IMO we can merge it now even if it's broken upstream

**Pull request merged**
