### PR TITLE
fix: ffmpeg (main)

### PR DESCRIPTION
**Pull request by martabal**
Possible fix for  #152.

Use ffmpeg from jellyfin repo

### CODE REVIEW

**Comment by hydazz** [comment]
whats the difference between ffmpeg and jellyfin-ffmpeg?

**Comment by martabal** [comment]
> whats the difference between ffmpeg and jellyfin-ffmpeg?

Possible fix for https://github.com/imagegenius/docker-immich/issues/152; this is the ffmpeg implementation Immich uses. But from my tests, it does not solve anything ...

**Comment by GlenLowland** [comment]
Hi. I want to try this PR. I've switched to the image tag for this PR and I get this in immich logs:
```
[Nest] 470  - 08/08/2023, 7:40:05 PM   ERROR [JobService] Unable to run job handler: Error: Cannot find ffprobe
[Nest] 470  - 08/08/2023, 7:40:05 PM   ERROR [JobService] Error: Cannot find ffprobe
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/ffprobe.js:145:31
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:194:9
    at wrapper (/app/immich/server/node_modules/async/dist/async.js:271:20)
    at next (/app/immich/server/node_modules/async/dist/async.js:5795:24)
    at /app/immich/server/node_modules/async/dist/async.js:327:20
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:186:13
    at /app/immich/server/node_modules/fluent-ffmpeg/lib/capabilities.js:123:9
    at wrapper (/app/immich/server/node_modules/async/dist/async.js:271:20)
    at next (/app/immich/server/node_modules/async/dist/async.js:5795:24)
    at /app/immich/server/node_modules/async/dist/async.js:327:20
```
So doesn't really even reach transcoding stage.

**Comment by martabal** [comment]
Yes the Dockerfile is incomplete for now, you need to create a symlink for ffmpeg and ffprobe

**Comment by GlenLowland** [comment]
Thanks for the help! So my results of testing this PR are:
- HEVC - ❌  (same as without this PR)
- VP9 - ✅ (doesn't work without the PR)
Strange that HEVC doesn't work as GPU supports it but even more strange VP9 works and I see gpu is being used during transcoding!

**Comment by GlenLowland** [comment]
Well, source file encoding doesn't matter. I have the same results as in previous comments when using H264 file as source.

**Comment by GlenLowland** [comment]
I think I've found the reason of such behaviour:
Jasper Lake supports only low-power mode when VP9/HEVC encoding:
https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#lp-mode-hardware-support

And, as of now, immich only uses LP mode for VP9 encoding on Intel GPU:
https://github.com/immich-app/immich/blob/e54cf914d70e6bba9618f898c8b9ae8a32d43811/server/src/domain/media/media.util.ts#L390

**Comment by martabal** [comment]
vp9 encoding works for you ?

**Comment by martabal** [comment]
bumped

**Comment by hydazz** [comment]
this one is ready?

**Comment by martabal** [comment]
It is !
I didn't notice any improvements from my side but according to @GlenLowland, it resolved its issue with transcoding to vp9

**Pull request merged**
